Refactored error codes
PDOK/geopackage-validator pull request #9
Opened 2020-09-17 12:14 UTC by botenvouwer

Added two recommendation checks proposed in [issue 7](https://github.com/PDOK/geopackage-validator/issues/7).

2020-09-17 12:16 UTC, botenvouwer commented
Gisteren al ingedient maar blijkbaar is er iets niet goed gegaan. Hierbij als nog. Ik ben nog bezig met toevoegen van unit tests voor deze twee recommendations.

2020-09-18 09:55 UTC, RoelvandenBerg requested changes
Lijkt me goed om er samen even doorheen te lopen. En een aantal van deze zaken even van te voren door te spreken. Het hernoemen van R naar RQ en RC is verder prima. Ik zou errors en warnings aanhouden, geen trace.

2020-09-18 09:55 UTC, RoelvandenBerg commented on geopackage_validator/validate.py
> +        used_validations.extend(json.load(json_file)["validations"])
Ter info: `+=` is in geval van lists syntactic sugar voor `[].extend()`

```suggestion
        used_validations += json.load(json_file)["validations"]
```

2020-09-18 09:55 UTC, RoelvandenBerg commented on geopackage_validator/validate.py
> +def get_validations_from_file(validations_path):
Deze functie maakt het zo iets minder leesbaar  wat mij betreft. Door pathlib te gebruiken zoals ik onderstaand aangeef kan je dit korter maken. Zo maak je het wel leesbaarder.

2020-09-18 09:55 UTC, RoelvandenBerg commented on geopackage_validator/validate.py
> +        used_validations.extend(json.load(json_file)["validations"])
Daarnaast is het niet nodig om eerst een lijst aan te maken en daarna te extenden. 

Dus: 
```python
def get_validations_from_file(validations_path):
    used_validations = []

    with open(validations_path) as json_file:
        used_validations = json.load(json_file)["validations"]
```

Wat ik nog mooier vind is pathlib.Path gebruiken: 
```python
validation_config_content = pathlib.Path(validations_path).read_text()
used_validations = json.load(validation_config_content)["validations"]
```

2020-09-18 09:55 UTC, RoelvandenBerg commented on geopackage_validator/validations_overview/validations_overview.py
> +    err_index: str, trace: List[str]
waarom trace? Ik vind errors mooier.

2020-09-18 09:55 UTC, RoelvandenBerg commented on tests/test_cli.py
> +    # assert '"errors": []' in result.output
Waarom comment je dit uit? Dit kan of weg of je laat dit staan en maakt een Jira ticket aan waarin je een voorstel doet dit aan te pakken. Liever geen todos in de code behalve als het echt nodig is.

2020-09-18 09:55 UTC, RoelvandenBerg commented on tests/validations/test_table_definitions_check.py
> +    )  # todo: Overwegen of we dit zo willen testen -> data structuur van de foutmelidng veranderen -> William heeft hier een voorstel voor
Liefst dit niet in de code opnemen. Graag even bespreken via PR comments, via het Jira ticket en/of slack.

2020-09-23 09:43 UTC, RoelvandenBerg approved these changes

2020-09-23 13:11 UTC, merged