Make /vsis3 or /vsicurl possible.
PDOK/geopackage-validator pull request #90
Opened 2022-03-02 16:55 UTC by RoelvandenBerg

# Omschrijving

Voegt in principe alleen functionaliteit toe. Maakt gebruik van vsicurl / vsis3 mogelijk waarmee gpkgs niet meer van minio worden binnengehaald. Mogelijke verbetering in de toekomst is eea standaard via minio te laten lopen. Daar nu vanaf gezien omdat gdal minio met vsis3 net ff wat anders benaderd dan we hier nu doen. 

Aangezien dit nieuwe functionaliteit toevoegd gaat de versie naar van 0.7.0. 
Tevens wat meer Pythonic  #boyscout refactoring van imports.

https://dev.kadaster.nl/jira/browse/PDOK-13859

## Type verandering

(Verwijder de opties die niet relevant zijn.)

- Nieuwe feature
- Verbetering oude feature
- Refactor
- Aanpassing van de configuratie

# Checklist:

- [X] Ik heb de code in deze PR zelf nogmaals nagekeken
- [X] Ik heb mijn code beter achtergelaten dan dat ik het aantrof
- [X] De code is leesbaar en de moeilijke onderdelen zijn voorzien van commentaar
- [X] Ik heb de tests toegevoegd/uitgebreid indien nodig
- [X] Ik heb de tests gedraaid die de werking van mijn wijziging bewijst
- [ ] De [PDOK documentatie](https://github.com/PDOK/interne-documentatie) is bijgewerkt indien nodig.
- [ ] Er zit geen gevoelig informatie in deze PR (wachtwoorden etc)

2022-03-02 19:05 UTC, roelarents approved these changes
goed

2022-03-03 06:59 UTC, kad-jagtt approved these changes

2022-03-03 07:37 UTC, WouterVisscher requested changes
Mis een stukje over /vsis3/ in de README

2022-03-03 09:40 UTC, RoelvandenBerg commented on geopackage_validator/utils.py
> +                gdal.SetConfigOption(gdal_env_parameter, v)
Deze moet volgens mji een inspringen naar links

2022-03-03 10:17 UTC, RoelvandenBerg commented on geopackage_validator/cli.py
> +    help="TRUE value, identifies the bucket via a virtual bucket host name, e.g.: mybucket.cname.domain.com - FALSE value, identifies the bucket as the top-level directory in the URI, e.g.: cname.dom
documentatie aangepast

2022-03-03 10:38 UTC, WouterVisscher commented
@RoelvandenBerg ik mis nog een voorbeeld call met `/vsis3`
Ik zie dat je het benoemd in de --help, maar ook als `/vsi`. En `/vsi` is geen GDAL call -> [doc](https://gdal.org/user/virtual_file_systems.html#network-based-file-systems).
Is dan het path naar de GPKG /vsi/{bucket}/{folder} of /vsis3/{bucket|/{folder}?

2022-03-03 12:57 UTC, WouterVisscher approved these changes

2022-03-03 16:54 UTC, merged